package com.timelordmod.gallifrey.world;

import com.timelordmod.gallifrey.world.dimension.ModDimensions;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents;
import net.minecraft.entity.player.PlayerEntity;

/** Runtime Mars behaviour. Terrain itself is generated by Mars' noise settings. */
public final class MarsWorldHandler {
    private MarsWorldHandler() {}

    public static void register() {
        // Mars gravity is approximately 38% of Earth's. Vanilla applies roughly
        // -0.08 vertical acceleration, so restoring +0.05 gives a close gameplay
        // approximation without modifying gravity globally for every dimension.
        ServerTickEvents.END_WORLD_TICK.register(world -> {
            if (!world.getRegistryKey().equals(ModDimensions.MARS_LEVEL_KEY)) return;
            for (PlayerEntity player : world.getPlayers()) {
                if (!player.isOnGround() && !player.isClimbing() && !player.isSwimming() && !player.hasNoGravity()) {
                    var velocity = player.getVelocity();
                    if (velocity.y < 0.0) {
                        player.setVelocity(velocity.x, velocity.y + 0.05, velocity.z);
                        player.velocityDirty = true;
                    }
                }
            }
        });
    }
}
